### ISSUE TITLE
Fields that have alternative forms

### ISSUE THREAD

**Issue by mnot** [ietf-wg-httpapi/deprecation-header#12]
... are considered a 'bad smell'. 

Instead of a date vs. a fixed string, could we just say that a date in the past is equal to 'true'?

**Comment by dret** [comment]
On 2021-07-29 08:31, Mark Nottingham wrote:
> ... are considered a 'bad smell'.
> Instead of a date vs. a fixed string, could we just say that a date in 
> the past is equal to 'true'?

i guess we could. and we already say that a date in the past means that 
the resource is deprecated. the motivation to allow a flag was to not 
force services to make up a date when they don't have one and simply 
want to flag something as deprecated. but we could also "force" them to 
make up a date by not allowing the "true" flag.

i am fine either way and i do see the point that the syntax may cause 
some implementations to not parse the field correctly. maybe others can 
weigh in as well?

**Comment by mnot** [comment]
FWIW, I see it like Expires -- if it's already stale, you just assign a date in the past.

**Comment by dret** [comment]
On Jul 31, 2021, at 06:46, Mark Nottingham ***@***.***> wrote:
> FWIW, I see it like Expires -- if it's already stale, you just assign a date in the past.
> 

i could definitely live with such a design.

**Comment by sdatspun2** [comment]
Having boolean helps align this header with OpenAPI's `deprecated` flag which does not require date. I wish that OpenAPI adds date for `deprecated`. 

>If the deprecation date is not known, the header field can carry the simple string "true", indicating that the resource context is deprecated, without indicating when that happened:

On Jul 31, 2021, at 06:46, Mark Nottingham ***@***.***> wrote:
 FWIW, I see it like Expires -- if it's already stale, you just assign a date in the past.

**Comment by mnot** [comment]
For Expires, January 1 1970 (epoch 0) is widely used.

**Comment by darrelmiller** [comment]
@sdatspun2  I wish OpenAPI supported deprecated date also.  But when we do, it won't be with a property that can be boolean or date.

**Comment by sdatspun2** [comment]
Ok @darrelmiller, thanks for clarification on the OpenAPI side of things.

I agree. We can just use date. There are some implementations out there, I would not know if any of those use boolean but since we are not an RFC yet, such a change should not be unexpected.

**Comment by dret** [comment]
it seems like we can safely remove the alternative syntax. i have created a PR asking for review by @mnot.
