### ISSUE TITLE
proposal to revert updated draft title

### ISSUE THREAD

**Issue by dret** [ietf-wg-httpapi/deprecation-header#2]
the draft used to be called "The Deprecation HTTP Header Field" and now is called "The Deprecation HTTP Header". i am not sure this change is intentional? technically speaking it is a header field, so i propose reverting to the original title.

**Comment by sdatgit** [comment]
@dret it was an oversight.

**Comment by sdatspun2** [comment]
@dret datatracker submission was raising some issue with the name and revision. i do not quite recall if that prompted me to try dropping "Field".

**Comment by dret** [comment]
On 2020-12-24 13:51, Sanjay Dalal wrote:
> @dret <https://github.com/dret> datatracker submission was raising some 
> issue with the name and revision. i do not quite recall if that prompted 
> me to try dropping "Field".

is it ok then to try to revert to the original title?

**Comment by sdatspun2** [comment]
Hello @richsalz what is your suggestion re how to make this change? is it possible for you to reject https://datatracker.ietf.org/submit/status/116473/ so I can submit a new one for rev 00?

**Comment by richsalz** [comment]
Submit a new draft with draft-ietf-httpapi-xxxxx with the new title.  You should be able to mark that it replaces the draft with the old title.  (if not, we can get it done).

**Comment by dret** [comment]
this was fixed by submitting -01 with the reverted title.
