### ISSUE TITLE
Removing link relation use with Link header

### ISSUE THREAD

**Issue by dret** [ietf-wg-httpapi/deprecation-header#20]
Re-reading #5 it seems we closed that one too early. Reading through where the draft currently uses link relations I think we need to clarify or to simplify.

- How is `alternate` supposed to be used, what's different from using the version-related link relations?
- @reschke's original concern still stands: We're "misusing" link relations that have a different specified purpose.
- If we're saying "don't auto-follow any of these", then @gabesullice's remark still holds: why not treat it as what we say it is, i.e. hints for humans, and say that these should be given in the resource that's linked to via `deprecation`?

Working on #14 it seems that this change would allow us to address 14 very effectively, because then we don't have to add all the language where we say "better don't treat the link relations in the way they're usually treated, i.e. as traversable links."

**Comment by dret** [comment]
My proposal for resolution is to remove all language around `successor-version`, `latest-version`, and `alternate`, and to add some language recommending to make this information discoverable via `deprecation`. @sdatspun2, what do you think?

**Comment by sdatspun2** [comment]
@dret 
>add some language recommending to make this information discoverable via deprecation

That does not harm. 

However, 

>My proposal for resolution is to remove all language around successor-version, latest-version, and alternate

We did not try to redefine these, we are just using these as defined in https://www.iana.org/assignments/link-relations/link-relations.xhtml. 

@reschke only `alternate` which is referred in HTML might be considered misused perhaps :) and we can remove. But `successor-version`, `latest-version` use the terms resources and this draft uses the same terms as well, literally and semantically. Do you agree or am I ignoring something obvious to you?

`latest-version`: When included on a versioned resource, this link points to a resource containing the latest (e.g., current) version.
`successor-version`: When included on a versioned resource, this link points to a resource containing the successor version in the version history.

**Comment by mnot** [comment]
No - 6829 is about navigating between revisions of a document under version control -- the concept of API versioning is a (potentially very) different thing. These link relations weren't defined for that, and a consumer that understands their semantics is going to be confused by this use. Agree with @dret - remove it all.

**Comment by sdatgit** [comment]
Ok

**Comment by sdatspun2** [comment]
>My proposal for resolution is to remove all language around successor-version, latest-version, and alternate
> These link relations weren't defined for that, and a consumer that understands their semantics is going to be confused by this use. ..Agree with @dret - remove it all.

Ok, single reltype for `deprecation`, it is then. API developer can provide additional documentation regarding alternate, successor, etc. versions on the documentation at that link.

**Comment by dret** [comment]
On 2022-06-10 01:47, Mark Nottingham wrote:
> No - 6829 is about navigating between revisions of a document under 
> version control -- the concept of API versioning is a (potentially very) 
> different thing. These link relations weren't defined for that, and a 
> consumer that understands their semantics is going to be confused by 
> this use. Agree with @dret <https://github.com/dret> - remove it all.

that was my point. a new API version may/will provide access to the same 
resource version (just providing a different way to interact with them), 
so the semantics are very different and potentially confusing.

**Comment by dret** [comment]
Closing after removing the link relation use as discussed.
