### ISSUE TITLE
link to HTTP IMF-fixdate is dangling; also http-date vs imf-fixdate

### ISSUE THREAD

**Issue by reschke** [ietf-wg-httpapi/deprecation-header#22]
I also note that Sunset uses http-date, which is a superset.

Restricting to imf-date is well-intended, but IMHO not a good idea as the assumption is that recipients will just use generic HTTP date parsers, right?

**Comment by dret** [comment]
On 2022-07-30 15:52, Julian Reschke wrote:
> I also note that Sunset uses http-date, which is a superset.
> 
> Restricting to imf-date is well-intended, but IMHO not a good idea as 
> the assumption is that recipients will just use generic HTTP date 
> parsers, right?

that's a good point, thanks. i'll leave this one open just in case we 
end up finishing "Deprecation" instead of starting "Lifecycle".

**Comment by dret** [comment]
Is this ok to close, @darrelmiller?

**Comment by sdatspun2** [comment]
@reschke can we close this now?

**Comment by sdatspun2** [comment]
Closing since the draft now uses sf-date
