### ISSUE TITLE
intro to header field inprecise

### ISSUE THREAD

**Issue by reschke** [ietf-wg-httpapi/deprecation-header#24]
> The Deprecation HTTP response header field allows a server to communicate to a client that the resource in context of the message is or will be deprecated.

What exactly does "in context of the message" mean? Is this about the resource being deprecated only in certain contexts (which?), or about the actual *resource* (URI) being deprecated depending on the request context?

**Comment by sdatspun2** [comment]
@reschke We mean resource on which HTTP method was invoked.

**Comment by richsalz** [comment]
@reschke do you think there should be additional wording or should we close this?  (If new wording, it can be done via WGLC)

**Comment by darrelmiller** [comment]
Closed due to inactivity.  Please feel free to reopen if necessary.
