### ISSUE TITLE
Confirming that "Deprecation" and "Sunset" use different data types

### ISSUE THREAD

**Issue by dret** [ietf-wg-httpapi/deprecation-header#28]
To avoid confusion, maybe there should be a short note to confirm that "Deprecation" and "Sunset" use different data types? It may look a bit odd at first sight. There's no need for a complete explanation, it could be as short as saying that the difference is there "for historical reasons".

**Comment by sdatspun2** [comment]
@dret thanks. I added a line, please take a look.

**Comment by dret** [comment]
Looks good to me. It's slightly odd that the data type is referred to as "Date" as it's a timestamp and not a (calendar) date, but that's what the definition of sf-date uses as terminology so it makes sense to stick with that.

**Comment by sdatspun2** [comment]
@dret Should you close this issue?
