### ISSUE TITLE
github issue management: permissions

### ISSUE THREAD

**Issue by dret** [ietf-wg-httpapi/deprecation-header#3]
@richsalz/@darrelmiller: it seems that we (the editors: @dret and @sdatgit/@sdatspun2) cannot freely assign issues in this repo? it looks like we can only do assignments to a list of predefined accounts (i was able to assign this issue here to @richsalz/@darrelmiller, but was unable to assign  #2 to @sdatgit/@sdatspun2).
maybe that's a side-effect of us being listed as contributors for the repo? is there a way to allow us to assign issues? it has been a very valuable function of @github to use (and that applies to the repos for linkset and warning header as well, managed in collaboration with @hvdsomp and @andrecedik, respectively).

**Comment by richsalz** [comment]
@dret made you a maintainer.  see if you can now assign issue #2.
(accidental choice, BTW, not deliberate.)

**Comment by dret** [comment]
On 2020-12-24 13:31, Rich Salz wrote:
> @dret <https://github.com/dret> made you a maintainer. see if you can 
> now assign issue #2 
> <https://github.com/ietf-wg-httpapi/deprecation-header/issues/2>.
> (accidental choice, BTW, not deliberate.)

thanks. i was able to assign the issue now. but this time @sdatspun2 
appeared in the list of choices (he wasn't there before). definitely 
works good enough for now! thanks!
