### ISSUE TITLE
minor editorial issues

### ISSUE THREAD

**Issue by reschke** [ietf-wg-httpapi/deprecation-header#36]
1. area is "Web and Internet Transport"
2. keyword "Internet-Draft" is meaningless, in particular when published as RFC. RFC-Editor will likely ask for more applicable keywords (maybe: "HTTP", "deprecation"...)
3. Intro referes to incorrect section of SFBIS (minor rephrasing suggested)
4. Definition of field value syntax should more closely follow suggestions from SFBIS and lose the ABNFish definition.

**Comment by richsalz** [comment]
@reschke thank you very much for your detailed review, interactions, and *for proposing fixes.* -- Rich, WG cochair
