### ISSUE TITLE
Inconsistency between text and the example

### ISSUE THREAD

**Issue by malevy** [ietf-wg-httpapi/deprecation-header#4]
There is a small inconsistency between the text and one of the example usages of the Deprecation header in draft-ietf-httpapi-deprecation-header.md. 

> The following example shows that the resource context has been deprecated on _Friday_, November 11, 2018 at 23:59:59 GMT:
> 
>     Deprecation: Sun, 11 Nov 2018 23:59:59 GMT

The correct day of the week for  November 11, 2018 was Sunday, according to Google.

**Comment by dret** [comment]
good catch, thanks!
