### ISSUE TITLE
Definition of resource context

### ISSUE THREAD

**Issue by darrelmiller** [ietf-wg-httpapi/deprecation-header#8]
>The Deprecation response header field describes the deprecation. It either shows the deprecation date, which may be in the future (the resource context will be deprecated at that date) or in the past (the resource context has been deprecated at that date), or it simply flags the resource context as being deprecated:

It is not clear to me the distinction between "resource" and "resource context".  Is the word "context" a significant qualifier?

**Comment by dret** [comment]
On 2021-03-21 00:11, Darrel wrote:
>     The Deprecation response header field describes the deprecation. It
>     either shows the deprecation date, which may be in the future (the
>     resource context will be deprecated at that date) or in the past
>     (the resource context has been deprecated at that date), or it
>     simply flags the resource context as being deprecated:
> 
> It is not clear to me the distinction between "resource" and "resource 
> context". Is the word "context" a significant qualifier?

that was the idea, but apparently it didn't succeed. the idea was that 
while the header field technically applies to the resource/URI, it also 
should be allowed to for example say "when the home document starts 
announcing deprecation, that applies to all resources of the API." that 
would make it possible to restrict usage of the deprecation header field 
to select resources (such as the home resource) while still allowing the 
header field to apply to the resource context (the API).

this is how sunset works as well, giving API providers the freedom to 
use it on all resources, or on select ones only.

https://tools.ietf.org/html/rfc8594#section-5

the disadvantage of this approach is that when used this way, 
deprecation/sunset will only be visibly announced to consumers when they 
interact with the resources that will carry those headers. but that's a 
decision that the API designer can make one way or the other.

-- 
erik wilde | ***@***.*** |
            | http://dret.net/netdret    |
            | http://twitter.com/dret    |

**Comment by darrelmiller** [comment]
I like the way the Sunset header spec is explicit about the fact that an API designer can document the fact that deprecation of one resource can signal the deprecation of related resources.  I don't think using the term "resource context" conveys it as clearly.

**Comment by dret** [comment]
On 2021-05-01 03:48, Darrel wrote:
> I like the way the Sunset header spec is explicit about the fact that an 
> API designer can document the fact that deprecation of one resource can 
> signal the deprecation of related resources. I don't think using the 
> term "resource context" conveys it as clearly.

ok, this makes sense. in that case it seems that the deprecation header 
spec should follow the wording of the sunset header spec more closely.

**Comment by dret** [comment]
@darrelmiller, would you be ok with the above proposal?

**Comment by darrelmiller** [comment]
@dret   Yes.

**Comment by dret** [comment]
@darrelmiller: i made the proposed change, if you're fine with it, feel free to close the issue. thanks for your contribution!
