### ISSUE TITLE
Clarification on multiplicity of deprecation links

### ISSUE THREAD

**Issue by darrelmiller** [ietf-wg-httpapi/deprecation-header#9]
The specification says:

> Servers MUST NOT include more than one Deprecation header field in the same response.

If two parts of the resource are deprecated at different times, what is the expected date in the deprecation header?  The first or last?

Regarding the deprecation link, the spec says:

> In addition to the Deprecation HTTP header field, the server can use links with the "deprecation" link relation type

Does the use of plural "links" indicate that multiple deprecation links can be included?

**Comment by dret** [comment]
On 2021-03-21 00:15, Darrel wrote:
> The specification says:
> 
>     Servers MUST NOT include more than one Deprecation header field in
>     the same response.
> 
> If two parts of the resource are deprecated at different times, what is 
> the expected date in the deprecation header? The first or last?

the spec cannot deprecate different parts of a response. deprecation of 
the resource always is done as a whole.

> Regarding the deprecation link, the spec says:
> 
>     In addition to the Deprecation HTTP header field, the server can use
>     links with the "deprecation" link relation type
> 
> Does the use of plural "links" indicate that multiple deprecation links 
> can be included?

no, that should be singular instead. good catch, thanks!

-- 
erik wilde | ***@***.*** |
            | http://dret.net/netdret    |
            | http://twitter.com/dret    |

**Comment by dret** [comment]
ooops, i was wrong. yes, multiple `deprecation`-typed links can be used, because they link to info/documentation. they could for example use link attributes such as media types or language to link to different resources.
